name: pre-commit

on:
  pull_request_target:
    types: [opened, reopened]
  push:
    branches: [main, linting-test]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Linting checks
        run: .github/workflows/pre-commit.sh
